on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: run tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install lcov
      run:  sudo apt-get install -y lcov
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install UI Deps
      run: npm ci
    # - name: NPM Audit
    #   run: npm audit
    - name: Build UI Assets
      run: make cmd/wego/ui/run/dist/main.js
    - name: Set up kubebuilder
      uses: fluxcd/pkg/actions/kubebuilder@main
    - name: Set up flux dir but let dependencies install flux
      run: mkdir -p pkg/flux/bin && tools/download-deps.sh $PWD/tools/dependencies.toml
    - name: Unit Tests with Coverage
      run: make coverage/merged.lcov
      env:
        KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: merged.lcov
